### PR TITLE
Fixing alignment

### LINKED ISSUE #231: buffer not aligned
I converted the pytorch checkpoint to safetensors. The buffer is not aligned

RWKV-4-Pile-430M-20220808-8066.pth is from https://huggingface.co/BlinkDL/rwkv-4-pile-430m
The convert script is here: https://github.com/iacore/rwkv-np/blob/main/convert.py

```
> xxd RWKV-4-Pile-430M-20220808-8066.safetensors | head -n 2
00000000: 66a7 0000 0000 0000 7b22 626c 6f63 6b73  f.......{"blocks
00000010: 2e30 2e61 7474 2e6b 6579 2e77 6569 6768  .0.att.key.weigh
```

The tensor data are all f32.

0xa766 % 4 == 2

Why not aligned: the offset count from after the metadata header (sized 0xa766).

### PR DESCRIPTION
**Pull request by Narsil**
Alignment was broken.

Simple logic failure (with pretty bad consequences):

- We're calculating how "unaligned" the header is. But we were adding the wrong padding to fix the alignment.
- Adding some test in the proptest to make sure it's aligned after reload
- Update the other tests

Fix #231

### CODE REVIEW

File: safetensors/src/tensor.rs [hunk 1]
```diff
@@ -194,7 +194,9 @@ fn prepare<S: AsRef<str> + Ord + std::fmt::Display, V: View, I: IntoIterator<Ite
     let mut metadata_buf = serde_json::to_string(&metadata)?.into_bytes();
     // Force alignment
     let extra = metadata_buf.len() % 8;
-    metadata_buf.extend(vec![b' '; extra]);
```
Comment (iacore) [inline safetensors/src/tensor.rs:197]: :frowning:

Comment (Narsil) [reply safetensors/src/tensor.rs:197]: Yes, bad blunder :(

**Review by OlivierDehaene — APPROVED** [review]
